name: Deploy to NCP Server

on:
  push:
    branches: [ ncp-migration ]
  pull_request:
    branches: [ ncp-migration ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build
      run: npm run build
      env:
        CI: false
        
    - name: Deploy to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.NCP_SERVER_IP }}
        username: ${{ secrets.NCP_SERVER_USER }}
        password: ${{ secrets.NCP_SERVER_PASSWORD }}
        source: "build/*"
        target: "/home/prometheus"
        strip_components: 1

    - name: Execute remote commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.NCP_SERVER_IP }}
        username: ${{ secrets.NCP_SERVER_USER }}
        password: ${{ secrets.NCP_SERVER_PASSWORD }}
        script: |
          cd /home/prometheus
          pm2 delete prometheus || true
          pm2 serve /home/prometheus 3000 --name prometheus 